### PR TITLE
Bump wasmparser to 0.58.0

### PR DESCRIPTION
**Pull request by abrown**
I believe this is necessary to get access to new instructions such as `bitmask`.

### CODE REVIEW

**Comment by abrown** [comment]
cc: @yurydelendik

**Comment by abrown** [comment]
Hm... branch names? https://github.com/bytecodealliance/wasm-tools/pull/36/checks?check_run_id=819643898#step:3:39

**Comment by alexcrichton** [comment]
Ok I pushed a few commits which I think fixes the benchmarking stuff. Turned out in the past few hours `cargo critcmp` was broken by criterion updates. What bad timing! I'll leave merging this up to @yurydelendik though.

**Comment by yurydelendik** [comment]
Thank you for the patch!

**Pull request merged**
