### PR TITLE
Provide public new method for Id AST node

### PR DESCRIPTION
**Pull request by martinitus**
Proposed fix for #135.

### CODE REVIEW

**Comment by martinitus** [comment]
Alternatively one could use `pub(crate)` fields in `Id` and drop the `new_unchecked` completely?

**Review by alexcrichton — COMMENTED** [review]
Thanks for this! Given how low-level this function is though I'd be tempted to say that the `new` function as-is is probably ok to export. If you think the behavior you added here though is useful, perhaps a `new` and `new_checked`?

**Comment by martinitus** [comment]
You are welcome! Thanks for all the work you are putting into this!<3

I thought about this once more and changed it to the pub(crate) variant as it aligns best with the rest of the code (imo) and avoids exposing a potential pitfall in the public API (e.g. passing in a `"invalid argument"` as name). The wast crate can simply instantiate the Id directly!

**Comment by alexcrichton** [comment]
Ok I think that's fine, but I think the `pub(crate)` can be removed from the fields since it's not necessary to construct an `Id` within the same module. Replacing the one instance of `Id::new` that was there prior I think is ok to use struct-construction syntax, however.

**Review by alexcrichton — APPROVED** [review]

**Pull request merged**
