### PR TITLE
[wast] Rename extern.internalize and extern.externalize

### PR DESCRIPTION
**Pull request by jpages**
The following instructions were renamed in wasm-gc (https://github.com/WebAssembly/gc/pull/447):

extern.internalize -> any.convert_extern
extern.externalize -> extern.convert_any

### CODE REVIEW

**Comment by jpages** [comment]
The tests should be fine (hopefully) once this PR is merged: https://github.com/WebAssembly/testsuite/pull/70

**Comment by alexcrichton** [comment]
Thanks! With that merged you should be able to include the submodule update as part of this PR

**Comment by jpages** [comment]
I had to update the submodule, and the snapshot files as well... 

Sorry, this PR turns out to bet more complex than expected.

**Review by alexcrichton — APPROVED** [review]
No worries, and thanks again!

**Pull request merged**
