### PR TITLE
threads: add validation for shared calls

### PR DESCRIPTION
**Pull request by abrown**
The shared-everything-threads [proposal] prevents `shared` contexts (e.g., in a `shared` function) from accessing unshared objects. This change adds validation to prevent `shared`-to-unshared calls.

[proposal]: https://github.com/WebAssembly/shared-everything-threads

### CODE REVIEW

**Comment by abrown** [comment]
cc: @alexcrichton, I have another branch that adds `shared` to `FuncType` but that doesn't seem quite right &mdash; no other composite type carries that along with it (but it would make things look nicer!).

**Comment by alexcrichton** [comment]
Hm how about making `CompositeType` an `enum` again? Basically move the `shared: bool` field into each of the enum arms. Then have something `fn shared(&self) -> bool` on `CompositeType` which accesses each variant?

**Comment by abrown** [comment]
> Hm how about making `CompositeType` an `enum` again? Basically move the `shared: bool` field into each of the enum arms. Then have something `fn shared(&self) -> bool` on `CompositeType` which accesses each variant?

Well, (1) that complicates parsing because we would have to pass down shared-ness into the variant parsing and (2) I think there's some argument to be made to keeping the wasm-tools AST close to the spec AST.

**Comment by alexcrichton** [comment]
To come back to this Andrew and I talked bit on Zulip about this and concluded the way to go might be to refactor `WasmResources` to only be able to return `&CompositeType` for a certain index. Existing func/struct/array accessors would all be removed. Then in the operator validator there would be helpers that would downcast this further to `&FuncType` and would auto-check for shared-ness which would avoid the need to thread around a boolean and make sure everything is checked everywhere.

**Comment by abrown** [comment]
In working on this, I was able to reuse the `*_type_at` helpers to add shareability checks but this only works when we retrieve by sub-type index; for some kinds of calls, we actually return the type by function index. If we want to get rid of the weird signature on `WasmModuleResources::type_of_function`, we might be able to just remove that entirely, call `WasmModuleResources::type_id_of_function` and use that ID with `func_type_at` (does that work?).

**Comment by alexcrichton** [comment]
Ah yeah I see, could that perhaps return just the `u32` type index of where the function's type is located in the module? (or `CoreTypeId` if that works, either way)

**Review by alexcrichton — APPROVED** [review]

**Pull request merged**
