### PR TITLE
wasmparser: Derive `Hash` for `{Memory,Global,Table}Type` 

### PR DESCRIPTION
**Pull request by fitzgen**
and bump to 0.79.0.

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]
I think this can actually be 0.78.2 since it looks API compatible? Otherwise looks good!

**Comment by fitzgen** [comment]
Wait. I might be confusing myself again. I think I need a subset of what's derived here, but let me double check.

**Comment by fitzgen** [comment]
Okay yeah I just needed `Hash` for `{Global, Memory, Table}Type` so I removed the other impls (which are bogus because e.g. `InstanceType` will hash differently depending on order of its exports even though it should be considered equal)

**Comment by fitzgen** [comment]
Also switched to 0.78.2 instead of 0.79.0

**Review by alexcrichton — APPROVED** [review]

**Pull request merged**
