### PR TITLE
Add iNxM.bitmask instructions

### PR DESCRIPTION
**Pull request by lars-t-hansen**
Add parsing, printing, etc for the new iNxM.bitmask instruction, see https://github.com/WebAssembly/simd/pull/201

### CODE REVIEW

**Comment by lars-t-hansen** [comment]
@alexcrichton, can you take a look? Thanks.

**Comment by alexcrichton** [comment]
Oh dear turns out I was accidentally not subscribed to this new repo, sorry about that!

Would y'all like a publish for the `wat` crate as well with this?

**Comment by lars-t-hansen** [comment]
Yes, a new version would be great, thanks!

**Comment by alexcrichton** [comment]
Sure thing, done!

**Pull request merged**
