### PR TITLE
Clarify license of the `wast` crate

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit fixes a mistake originating from 6ae3b271 where when the
crate was originally relicensed from "MIT/Apache-2.0" to "Apache-2.0
WITH LLVM-exception" I forgot to delete the corresponding license files
or update time. The `Cargo.toml` of `wast` says that it has the
"Apache-2.0 WITH LLVM-exception" license but the license files
themselves still look like "MIT/Apache-2.0". This clarifies the
situation by deleting the extraneous files to inherit the repository's
"Apache-2.0 WITH LLVM-exception" license.

To be extra-conservative here I'm going to ask for the sign-off of anyone who
has previously modified the `wast` crate. I've cc'd the authors below and if
you are ok with this change it would be great if you could comment as such or
approve the PR.

* [x] @alexcrichton
* [x] @abrown
* [x] @takikawa
* [x] @hvithrafn
* [x] @Hywan
* [x] @lars-t-hansen
* [x] @fitzgen
* [x] @pchickey
* [x] @eqrion
* [x] @pepyakin
* [x] @tschneidereit
* [x] @yurydelendik

### CODE REVIEW

**Review by fitzgen — APPROVED** [review]

**Review by abrown — APPROVED** [review]

**Review by pepyakin — APPROVED** [review]

**Review by pchickey — APPROVED** [review]

**Comment by hvithrafn** [comment]
@alexcrichton I approve these changes.

**Comment by lars-t-hansen** [comment]
@alexcrichton, I am fine with this clarification.

**Comment by takikawa** [comment]
@alexcrichton I am fine with the license clarification as well.

**Comment by eqrion** [comment]
@alexcrichton I approve these changes.

**Comment by alexcrichton** [comment]
@Hywan would you be up for taking a look at this? It'd be great to get this taken care of to avoid any future confusion!

For reference if you're curious these are the changes that you've authored in this repository:

* 64b5091a27a4be17883f44437f06f621c80367ab
* d31367323ab097c18e2047f01a99c709731f4934

**Comment by Hywan** [comment]
@alexcrichton I approve these changes :-).

**Comment by alexcrichton** [comment]
Ok thanks everyone!

**Pull request merged**
