### PR TITLE
Added the ability to add features when decoding Wasm with wit-component

### PR DESCRIPTION
**Pull request by silesmo**
Added the ability to add features when decoding Wasm with wit-component
This is something I needed to get the WASM Analyzer working with arbitrary Wasm files as some Wasm files had features enabled that wasn't supported with the default features used in wit-component.

### CODE REVIEW

**Comment by silesmo** [comment]
@peterhuene

**Comment by alexcrichton** [comment]
Thanks! For this use case though I think it'd be ok to unconditionally enable all the various features. This isn't a first-class validation step for the core wasm itself and ideally this wouldn't validate core wasm at all. Given how internal it is though I think it's ok to avoid the need for configuration here.

**Comment by silesmo** [comment]
Updated so all features are always enabled @alexcrichton

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
