### PR TITLE
wast: Add exnref, try_table, and throw_ref

### PR DESCRIPTION
**Pull request by eqrion**
These types and instructions are part of the exception handling rework tracked in (https://github.com/WebAssembly/exception-handling/issues/281).

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]
Thanks! I think this needs a rustfmt but should otherwise be good to go.

**Comment by eqrion** [comment]
Just did the rustfmt, but hold up on merging there's been some recent bikeshedding of the binary to work through. I will probably update again.

**Comment by eqrion** [comment]
@alexcrichton Okay, this should be good to go now.

**Review by alexcrichton — APPROVED** [review]

**Comment by alexcrichton** [comment]
Would you like a crates.io release for this?

**Comment by alexcrichton** [comment]
Sure thing, doing that in https://github.com/bytecodealliance/wasm-tools/pull/1227

**Pull request merged**
