### PR TITLE
Update testsuite submodule to dc27dad3e34e466bdbfea32fe3c73f5e31f88560

### PR DESCRIPTION
**Pull request by fitzgen**

### CODE REVIEW

**Comment by alexcrichton** [comment]
I was a bit curious where all the new tests came from and now I'm a bit confused. The [comparison of the submodules](https://github.com/WebAssembly/testsuite/compare/26d62d0ad297b14218807cd20d9b568e11ec7bd9...dc27dad3e34e466bdbfea32fe3c73f5e31f88560) doesn't actually contain any meaningful changes, which makes me curious what's going on here.

I don't think that the snapshot logic accounts for deleted tests well, so are these extra files perhaps leftover on your machine from some previous runs? (I suppose if you delete them and re-run with `BLESS=1` do they reappear?) 

Although you're adding new code here like `AssertMalformedCustom` which I presume you ran into an issue to do that. So now that I type this out, is there perhaps a forgotten submodule update here?

**Comment by fitzgen** [comment]
Not sure what's going on. I blew away the snaphots, ran `git clean -f -x -d` in the submodule, and then re-ran tests with `BLESS=1` and there aren't any changes.

**Comment by fitzgen** [comment]
Also, that comparison between submodules you linked seems wrong? Because I know that there were changes to GC tests, which is the whole reason I'm doing this PR. Not sure what is going on here.

**Comment by fitzgen** [comment]
Or did someone else update the testsuite repo in the last couple weeks?

**Comment by alexcrichton** [comment]
https://github.com/bytecodealliance/wasm-tools/pull/1298 was the latest PR to update the submodule which I think may have included the changes you're looking for? The diff is the difference of the submodule commit on this repo's `main` branch vs the `testsuite` repo's `main` branch.

Updating the submodule locally and blowing away the `tests/snapshots` folder doesn't yield any changes relative to `main` locally for me, so I'm also preplexed as to what's happening...

**Comment by alexcrichton** [comment]
This is adding a `tests/snapshots/testsuite/repos` folder which doesn't currently exist which I think is generated from the update script, so it may be that the `clean` in the submodule itself didn't clean up this folder? I think that may be because `git clean` doesn't remove submodules

**Comment by alexcrichton** [comment]
As in, `tests/testsuite/repos/*` probably has a bunch of stuff for you in the submodule of the `wasm-tools` checkout you have, and if you remove all that manually I think most of these files should disappear.

That being said I think that many changes here may not be necessary after #1298?

**Pull request closed without merging**
