### PR TITLE
converter from wit-parser Resolve to wit-encoder packages

### PR DESCRIPTION
**Pull request by MendyBerger**
Also improves the interface `use` api

### CODE REVIEW

**Review by alexcrichton — APPROVED** [review]
Nice!

**Comment by alexcrichton** [comment]
I think the test might be due to line endings, so perhaps having it as an in-file literal instead?

**Comment by MendyBerger** [comment]
@alexcrichton can confirm that line endings are indeed the problem here.
How do you feel about a manual `.replace("\r\n", "\n")`? I don't think that `wit-parser` can just read text without a file.

**Comment by alexcrichton** [comment]
Would [`Resolve::push_str`](https://docs.rs/wit-parser/latest/wit_parser/struct.Resolve.html#method.push_str) work for that?

**Comment by MendyBerger** [comment]
Missed that one. Should work!

**Pull request merged**
