### PR TITLE
Update GC proposal parsing

### PR DESCRIPTION
**Pull request by eqrion**
These commits improves `wast`'s support for the typed-function-references and gc proposals.

### CODE REVIEW

**Comment by eqrion** [comment]
Taking a look at the benchmarking failure.

**Comment by alexcrichton** [comment]
Thanks for this! The benchmarking failure is probably unrelated to this, but could you add some tests exercising the `let` syntax here too? (ideally we'd have a test for all the syntaxes, at least at a smoke level, but I didn't check how much of our existing tests cover this).

Also the function-references proposal was recently merged into the `testsuite` repo, so it this something that we should look into parsing perhaps? (in that, does `wat` today have enough support to parse all the `*.wast` files in that folder?)

**Comment by alexcrichton** [comment]
👍

**Comment by alexcrichton** [comment]
FWIW these are the parse failures at least I see parsing the function-references proposal:

```
failed test: tests/testsuite/proposals/function-references/br_on_null.wast

Caused by:
    unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
         --> tests/testsuite/proposals/function-references/br_on_null.wast:20:66
          |
       20 |   (func (export "nullable-null") (result i32) (call $n (ref.null (type $t))))
          |                                                                  ^
failed test: tests/testsuite/proposals/function-references/br_table.wast

Caused by:
    unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
         --> tests/testsuite/proposals/function-references/br_table.wast:1289:41
          |
     1289 |         (br_table $l1 $l2 $l1 (ref.null (type $t)) (local.get 0))
          |                                         ^
failed test: tests/testsuite/proposals/function-references/call_ref.wast

Caused by:
    unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
         --> tests/testsuite/proposals/function-references/call_ref.wast:22:39
          |
       22 |     (call_ref (i32.const 1) (ref.null (type $ii)))
          |                                       ^
failed test: tests/testsuite/proposals/function-references/func_bind.wast

Caused by:
    unexpected token, expected an identifier or u32
         --> tests/testsuite/proposals/function-references/func_bind.wast:8:16
          |
        8 |     (func.bind (type $unop) (local.get $i) (ref.func $add))
          |                ^




    	failed directive on tests/testsuite/proposals/function-references/let.wast:196:2

    	Caused by:
    	    duplicate local identifier
    	         --> tests/testsuite/proposals/function-references/let.wast:199:17
    	          |
    	      199 |     (let (local $x i32) (return (local.get $x)))
    	          |                 ^

failed test: tests/testsuite/proposals/function-references/linking.wast

Caused by:
    unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
         --> tests/testsuite/proposals/function-references/linking.wast:101:62
          |
      101 |   (global (export "g-const-refnull") (ref null $t) (ref.null (type $t)))
          |                                                              ^
failed test: tests/testsuite/proposals/function-references/ref.wast

Caused by:
    unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
         --> tests/testsuite/proposals/function-references/ref.wast:12:12
          |
       12 |       (ref (type 0))
          |            ^
failed test: tests/testsuite/proposals/function-references/ref_as_non_null.wast

Caused by:
    unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
         --> tests/testsuite/proposals/function-references/ref_as_non_null.wast:14:66
          |
       14 |   (func (export "nullable-null") (result i32) (call $n (ref.null (type $t))))
          |                                                                  ^
failed test: tests/testsuite/proposals/function-references/ref_is_null.wast

Caused by:
    unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
         --> tests/testsuite/proposals/function-references/ref_is_null.wast:15:25
          |
       15 |     (call $f3 (ref.null (type $t)))
          |                         ^
failed test: tests/testsuite/proposals/function-references/ref_null.wast

Caused by:
    unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
         --> tests/testsuite/proposals/function-references/ref_null.wast:5:57
          |
        5 |   (func (export "ref") (result (ref null $t)) (ref.null (type $t)))
          |                                                         ^
failed test: tests/testsuite/proposals/function-references/return_call_ref.wast

Caused by:
    unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
         --> tests/testsuite/proposals/function-references/return_call_ref.wast:103:32
          |
      103 |     (return_call_ref (ref.null (type $proc)))
          |                                ^
failed test: tests/testsuite/proposals/function-references/select.wast

Caused by:
    unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
         --> tests/testsuite/proposals/function-references/select.wast:271:64
          |
      271 | (assert_return (invoke "join-funcnull" (i32.const 0)) (ref.null))
          |                                                                ^
```

@eqrion do you think anything there is worth addressing? Otherwise I'd be happy to go ahead and publish this.

**Comment by eqrion** [comment]
> FWIW these are the parse failures at least I see parsing the function-references proposal:
> 
> ```
> failed test: tests/testsuite/proposals/function-references/br_on_null.wast
> 
> Caused by:
>     unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
>          --> tests/testsuite/proposals/function-references/br_on_null.wast:20:66
>           |
>        20 |   (func (export "nullable-null") (result i32) (call $n (ref.null (type $t))))
>           |                                                                  ^
> failed test: tests/testsuite/proposals/function-references/br_table.wast
> 
> Caused by:
>     unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
>          --> tests/testsuite/proposals/function-references/br_table.wast:1289:41
>           |
>      1289 |         (br_table $l1 $l2 $l1 (ref.null (type $t)) (local.get 0))
>           |                                         ^
> failed test: tests/testsuite/proposals/function-references/call_ref.wast
> 
> Caused by:
>     unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
>          --> tests/testsuite/proposals/function-references/call_ref.wast:22:39
>           |
>        22 |     (call_ref (i32.const 1) (ref.null (type $ii)))
>           |                                       ^
> failed test: tests/testsuite/proposals/function-references/func_bind.wast
> 
> Caused by:
>     unexpected token, expected an identifier or u32
>          --> tests/testsuite/proposals/function-references/func_bind.wast:8:16
>           |
>         8 |     (func.bind (type $unop) (local.get $i) (ref.func $add))
>           |                ^
> 
> 
> 
> 
>     	failed directive on tests/testsuite/proposals/function-references/let.wast:196:2
> 
>     	Caused by:
>     	    duplicate local identifier
>     	         --> tests/testsuite/proposals/function-references/let.wast:199:17
>     	          |
>     	      199 |     (let (local $x i32) (return (local.get $x)))
>     	          |                 ^
> 
> failed test: tests/testsuite/proposals/function-references/linking.wast
> 
> Caused by:
>     unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
>          --> tests/testsuite/proposals/function-references/linking.wast:101:62
>           |
>       101 |   (global (export "g-const-refnull") (ref null $t) (ref.null (type $t)))
>           |                                                              ^
> failed test: tests/testsuite/proposals/function-references/ref.wast
> 
> Caused by:
>     unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
>          --> tests/testsuite/proposals/function-references/ref.wast:12:12
>           |
>        12 |       (ref (type 0))
>           |            ^
> failed test: tests/testsuite/proposals/function-references/ref_as_non_null.wast
> 
> Caused by:
>     unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
>          --> tests/testsuite/proposals/function-references/ref_as_non_null.wast:14:66
>           |
>        14 |   (func (export "nullable-null") (result i32) (call $n (ref.null (type $t))))
>           |                                                                  ^
> failed test: tests/testsuite/proposals/function-references/ref_is_null.wast
> 
> Caused by:
>     unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
>          --> tests/testsuite/proposals/function-references/ref_is_null.wast:15:25
>           |
>        15 |     (call $f3 (ref.null (type $t)))
>           |                         ^
> failed test: tests/testsuite/proposals/function-references/ref_null.wast
> 
> Caused by:
>     unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
>          --> tests/testsuite/proposals/function-references/ref_null.wast:5:57
>           |
>         5 |   (func (export "ref") (result (ref null $t)) (ref.null (type $t)))
>           |                                                         ^
> failed test: tests/testsuite/proposals/function-references/return_call_ref.wast
> 
> Caused by:
>     unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
>          --> tests/testsuite/proposals/function-references/return_call_ref.wast:103:32
>           |
>       103 |     (return_call_ref (ref.null (type $proc)))
>           |                                ^
> failed test: tests/testsuite/proposals/function-references/select.wast
> 
> Caused by:
>     unexpected token, expected one of: `func`, `extern`, `any`, `exn`, `eq`, `i31`, an index
>          --> tests/testsuite/proposals/function-references/select.wast:271:64
>           |
>       271 | (assert_return (invoke "join-funcnull" (i32.const 0)) (ref.null))
>           |                                                                ^
> ```
> 
> @eqrion do you think anything there is worth addressing? Otherwise I'd be happy to go ahead and publish this.

Sorry, I should have communicated more. I'm currently working on these failures and should have some more commits in a bit that should fix those.

**Comment by alexcrichton** [comment]
Oh oops my bad, in that case no worries! I should probably be a little less trigger-happy anyway.

**Comment by alexcrichton** [comment]
Ok sorry yeah I'm definitely too trigger happy. Looking more at that failure with benchmarks I think it's actually caused by this PR, so I pushed a revert of this PR to the `main` branch of the repo. It's probably just a test which needs to be ignore (or an error somewhere) or something like that though in the benchmark script.

**Comment by eqrion** [comment]
Okay, I'll take a look at the benchmark failure next, I have the function-reference failures figured out. I'll probably open a new PR, don't think this one can be re-used now that the commit has been merged.

**Comment by alexcrichton** [comment]
Ah yeah that's true, sorry about that :(

**Comment by eqrion** [comment]
Not a problem! I'm glad you pointed me at the official tests, it's shaking some bugs out.

**Pull request merged**
