### PR TITLE
wit-component: Add WitPrinter::emit_docs option

### PR DESCRIPTION
**Pull request by lann**
Add a configuration option and implementation to print doc comments with associated items.

### CODE REVIEW

**Comment by lann** [comment]
The existing test harnesses don't support this as they all transcode through binary wasm or wat. I'm planning to work on adding doc comments to the binary encoding next, so this change can either wait for that to gain testing or be merged as-is.

**Comment by lann** [comment]
A couple of questions about the implementation:

- Should `emit_docs` even be optional?
  - Should it default to `true`?
  - Should it support emitting block-doc comments (`/** ... */`)?

**Comment by sunfishcode** [comment]
> A couple of questions about the implementation:
> 
>     * Should `emit_docs` even be optional?

Yes, it seems reasonable to have an option.
      
>       * Should it default to `true`?

Yes!

>       * Should it support emitting block-doc comments (`/** ... */`)? (e.g. `.emit_docs(DocFormat::Block)` or something)

Only if someone really wants it; I wouldn't speculatively add it.

**Review by alexcrichton — APPROVED** [review]
This all looks great to me, thanks! Happy to merge when you feel it's ready (and I think it's ok to merge at any time even if the binary format doesn't encode comments yet)

**Comment by lann** [comment]
Based on my last round of manual testing I _think_ I'm printing docs everywhere that `Resolve` is parsing them now.

**Pull request merged**
