### PR TITLE
SIMD: Add i64x2.all_true, i64x2.eq, i64x2.ne

### PR DESCRIPTION
**Pull request by yurydelendik**
See https://github.com/WebAssembly/simd/pull/381, https://github.com/WebAssembly/simd/pull/411, https://github.com/WebAssembly/simd/pull/415. These have been accepted into the spec.

TODO:
- [x] binary encodings <del>for `i64x2.eq` and `i64x2.ne`</del>

### CODE REVIEW

**Comment by yurydelendik** [comment]
atm selecting `0xfd c0` for "i64x2.eq" (based on the code in binaryen), and `0xfd c2` for "i64x2.ne"

**Review by alexcrichton — APPROVED** [review]
Thanks! Should merging hold off though until the upstream opcodes are assigned numbers?

**Comment by yurydelendik** [comment]
> Should merging hold off though until the upstream opcodes are assigned numbers?

Probably. I think `0xfd c0` will stay, not sure about other one. @lars-t-hansen ?

**Comment by lars-t-hansen** [comment]
i64x2.all_true also appears to be a mess: https://github.com/WebAssembly/simd/pull/415#issuecomment-768677362, a consequence of insisting on "logical" blocks of instructions while not setting aside large enough open spaces, combined with a bug in V8 that disallows opcodes > 255.

**Comment by alexcrichton** [comment]
Well in any case y'all are much more up-to-date on simd than I am anyway, so I'm happy to merge whenever y'all are comfortable about the opcodes.

**Comment by yurydelendik** [comment]
encoding from https://chromium.googlesource.com/v8/v8.git/+/refs/heads/master/src/wasm/wasm-opcodes.h#350

**Pull request merged**
